services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: docker/Gateway.Dockerfile
    ports:
     - "5001:5001"
    environment:
     - IS_DOCKER=true
networks:
  default:
    name: "mint"