services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
     - "5001:5001"
    environment:
     - IS_DOCKER=true
    volumes:
      - ./:/mint/mint-services

networks:
  default:
    name: "mint"