version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - IS_DOCKER=true

networks:
  default:
    external:
      name: gateway_network